# Generated by Django 6.1.1 on 2026-09-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='quoted_price',
            new_name='admin_quote_amount',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='additional_notes',
            new_name='admin_response_notes',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Specific requirements or customization details'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Starting price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='design_file',
            field=models.FileField(help_text='Upload your blueprint or design file', upload_to='design_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.product'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Quote Sent'), ('approved', 'Approved / Paid'), ('rejected', 'Rejected'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
