# Generated by Django 6.1.1 on 2026-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='MEKLAS', max_length=100)),
                ('contact_phone', models.CharField(default='(+254) 747900900', max_length=20)),
                ('top_bar_message', models.CharField(default='Track My Order', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
